version: '3.9'
services:
  kiwix-server:
    image: ghcr.io/kiwix/kiwix-serve
    container_name: kiwix-server
    restart: unless-stopped
    command:
      - /data/*.zim
    expose:
      - "8080"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8080 || exit 1"]
      interval: 30s
      timeout: 4s
      retries: 2
      start_period: 10s
    networks:
      kiwix_network:
    volumes:
      - /volume2/docker/kiwix/data:/data:ro

  proxy:
    image: nginx:latest
    container_name: kiwix-proxy
    restart: unless-stopped
    depends_on:
      - kiwix-server
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 4s
      retries: 2
      start_period: 10s
    networks:
      kiwix_network:
      eth5_macvlan:
        ipv4_address: 172.30.1.35
    volumes:
      - /volume2/docker/kiwix/proxy/logs:/var/log/nginx:rw
      - /volume2/docker/kiwix/proxy/nginx.conf:/etc/nginx/nginx.conf:ro


networks:
  kiwix_network:
    driver: bridge
    driver_opts:
       com.docker.network.bridge.enable_ip_masquerade: 'false'
    internal: true
  eth5_macvlan:
    name: eth5_macvlan
    external: true
