global:
  scrape_interval:	   20s
  evaluation_interval: 20s

scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 10s
    metrics_path: '/cadvisor/metrics'
    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: 'node_exporter'
    scrape_interval: 10s
    metrics_path: '/node_exporter/metrics'
    static_configs:
      - targets: ['node_exporter:9100']
